[2024-06-16T00:33:40.289+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T00:33:40.329+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2024-06-15T19:03:17.699454+00:00 [queued]>
[2024-06-16T00:33:40.346+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2024-06-15T19:03:17.699454+00:00 [queued]>
[2024-06-16T00:33:40.346+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-16T00:33:40.400+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_to_postgresql> on 2024-06-15 19:03:17.699454+00:00
[2024-06-16T00:33:40.413+0530] {standard_task_runner.py:63} INFO - Started process 333529 to run task
[2024-06-16T00:33:40.422+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'get_university_api_send_psql', 'send_to_postgresql', 'manual__2024-06-15T19:03:17.699454+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp3f8q3cy2']
[2024-06-16T00:33:40.425+0530] {standard_task_runner.py:91} INFO - Job 97: Subtask send_to_postgresql
[2024-06-16T00:33:40.548+0530] {task_command.py:426} INFO - Running <TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2024-06-15T19:03:17.699454+00:00 [running]> on host Mohammed-Raza.
[2024-06-16T00:33:40.695+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_university_api_send_psql' AIRFLOW_CTX_TASK_ID='send_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T19:03:17.699454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T19:03:17.699454+00:00'
[2024-06-16T00:33:40.696+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T00:33:41.023+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T00:33:41.025+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mohdraza/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mohdraza/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mohdraza/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mohdraza/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/mohdraza/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/mohdr/Documents/airflow/dags/main.py", line 103, in _send_to_postgresql
    conn = psycopg2.connect(
  File "/home/mohdraza/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.0.108), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-06-16T00:33:41.060+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=get_university_api_send_psql, task_id=send_to_postgresql, run_id=manual__2024-06-15T19:03:17.699454+00:00, execution_date=20240615T190317, start_date=20240615T190340, end_date=20240615T190341
[2024-06-16T00:33:41.107+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task send_to_postgresql (connection to server at "host.docker.internal" (192.168.0.108), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 333529)
[2024-06-16T00:33:41.120+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T00:33:41.149+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T00:33:41.176+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
